nelmio_api_doc:
  documentation:
    info:
      title: Streaming service core API
      description: Streaming service core API!
      version: 1.0.0
    components:
      securitySchemes:
        Bearer:
          type: http
          scheme: bearer
          bearerFormat: JWT
          description: "JWT token obtained from /api/v1/internal/signin endpoint"
    security:
      - Bearer: []
  areas:
    default:
      path_patterns: [^/api]
      host_patterns: [^api\.]
    v1_internal:
      path_patterns: [^/api/v1/internal]
      documentation:
        info:
          title: Streaming service core internal API
          description: Streaming service core internal API used for admin purposes
          version: 1.0.0
