# See https://github.com/snc/SncRedisBundle/blob/master/docs/README.md for instructions on
snc_redis:
  clients:
    default:
      type: predis
      alias: default
      dsn: "%env(REDIS_URL)%"
      logging: false
      options:
        parameters:
          password: "%env(REDIS_PASSWORD)%"
        prefix: "%env(REDIS_PREFIX)%"
