healthz:
  path: /healthz
  controller: App\UI\Http\Rest\Internal\Controller\V1\Healthz\HealthzController::__invoke
  methods: GET

##User
confirm_email:
  path: /confirm-email
  controller: App\UI\Http\Rest\Internal\Controller\V1\User\ConfirmEmailController::__invoke
  methods: GET
users_list:
  path: /users
  controller: App\UI\Http\Rest\Internal\Controller\V1\User\GetUsersController::__invoke
  methods: GET

users_single:
  path: /users/{uuid}
  controller: App\UI\Http\Rest\Internal\Controller\V1\User\GetUserByIdController::__invoke
  methods: GET

users_create:
  path: /users
  controller: App\UI\Http\Rest\Internal\Controller\V1\User\CreateUserController::__invoke
  methods: POST

users_update:
  path: /users/{uuid}
  controller: App\UI\Http\Rest\Internal\Controller\V1\User\UpdateUserByIdController::__invoke
  methods: POST

users_delete:
  path: /users/{uuid}
  controller: App\UI\Http\Rest\Internal\Controller\V1\User\DeleteUserByIdController::__invoke
  methods: DELETE


##Account
accounts_list:
  path: /accounts
  controller: App\UI\Http\Rest\Internal\Controller\V1\Account\GetAccountsController::__invoke
  methods: GET

accounts_single:
  path: /accounts/{uuid}
  controller: App\UI\Http\Rest\Internal\Controller\V1\Account\GetAccountByIdController::__invoke
  methods: GET

accounts_create:
  path: /accounts
  controller: App\UI\Http\Rest\Internal\Controller\V1\Account\CreateAccountController::__invoke
  methods: POST

accounts_update:
  path: /accounts/{uuid}
  controller: App\UI\Http\Rest\Internal\Controller\V1\Account\UpdateAccountByIdController::__invoke
  methods: POST

accounts_delete:
  path: /accounts/{uuid}
  controller: App\UI\Http\Rest\Internal\Controller\V1\Account\DeleteAccountByIdController::__invoke
  methods: DELETE

##Video
videos_list:
  path: /videos
  controller: App\UI\Http\Rest\Internal\Controller\V1\Video\GetVideosController::__invoke
  methods: GET

videos_single:
  path: /videos/{uuid}
  controller: App\UI\Http\Rest\Internal\Controller\V1\Video\GetVideoByIdController::__invoke
  methods: GET

videos_create:
  path: /videos
  controller: App\UI\Http\Rest\Internal\Controller\V1\Video\CreateVideoController::__invoke
  methods: POST

videos_update:
  path: /videos/{uuid}
  controller: App\UI\Http\Rest\Internal\Controller\V1\Video\UpdateVideoByIdController::__invoke
  methods: POST

videos_delete:
  path: /videos/{uuid}
  controller: App\UI\Http\Rest\Internal\Controller\V1\Video\DeleteVideoByIdController::__invoke
  methods: DELETE

##VideoComment
video_comments_list:
  path: /video-comments
  controller: App\UI\Http\Rest\Internal\Controller\V1\VideoComments\GetVideoCommentsController::__invoke
  methods: GET

video-comments_single:
  path: /video-comments/{uuid}
  controller: App\UI\Http\Rest\Internal\Controller\V1\VideoComments\GetVideoCommentsByIdController::__invoke
  methods: GET

video-comments_create:
  path: /video-comments
  controller: App\UI\Http\Rest\Internal\Controller\V1\VideoComments\CreateVideoCommentsController::__invoke
  methods: POST


video-comments_update:
  path: /video-comments/{uuid}
  controller: App\UI\Http\Rest\Internal\Controller\V1\VideoComments\UpdateVideoCommentsByIdController::__invoke
  methods: POST

video-comments_delete:
  path: /video-comments/{uuid}
  controller: App\UI\Http\Rest\Internal\Controller\V1\VideoComments\DeleteVideoCommentsByIdController::__invoke
  methods: DELETE

# Authentication routes
signup:
  path: /signup
  controller: App\UI\Http\Rest\Internal\Controller\V1\User\CreateUserController::__invoke
  methods: POST

signin:
  path: /signin
  controller: App\UI\Http\Rest\Internal\Controller\V1\Auth\SignInController::__invoke
  methods: POST

refresh_token:
  path: /refresh-token
  controller: App\UI\Http\Rest\Internal\Controller\V1\Auth\RefreshTokenController::__invoke
  methods: POST

revoke_token:
  path: /revoke-token
  controller: App\UI\Http\Rest\Internal\Controller\V1\Auth\RevokeTokenController::__invoke
  methods: POST
