# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
  upload_video_dir: '%kernel.project_dir%/%env(UPLOAD_VIDEO_DIR)%'

services:
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  # Default resource configuration for the App namespace
  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'

  App\UI\Http\Rest\Internal\Controller\:
    resource: '../src/UI/Http/Rest/Internal/Controller/'
    tags: [ 'controller.service_arguments' ]

  App\Application\Shared\Validator\UniqueEmailValidator:
    arguments:
      $userRepository: '@App\Infrastructure\Core\User\Repository\UserRepository'
    tags: [ 'validator.constraint_validator' ]

  App\Infrastructure\Shared\EventListener\ExceptionListener:
    tags:
      - { name: kernel.event_listener, event: kernel.exception }

  App\Infrastructure\Shared\Mailer\UserMailer:
    arguments:
      $secretKey: '%env(EMAIL_CONFIRMATION_SECRET_KEY)%'

  #  VALIDATORS
  App\Domain\Core\User\Validator\Constraints\ConfirmEmailRequestConstraintValidator:
    arguments:
      $secretKey: '%env(EMAIL_CONFIRMATION_SECRET_KEY)%'
      $userRepository: '@App\Domain\Core\User\Repository\UserRepositoryInterface'
      $userConfirmationService: '@App\Infrastructure\Shared\Services\User\UserConfirmationService'
    tags:
      - { name: validator.constraint_validator, alias: app_valid_signature_validator }

  App\Infrastructure\Shared\Validation\RequestValidatorListener:
    tags:
      - { name: kernel.event_listener, event: kernel.controller }